# Generated by Django 3.0.6 on 2020-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteviewer', '0005_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='siteviewer.Image'),
        ),
    ]
